# Generated by Django 4.1.2 on 2023-03-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_app', '0003_remove_decline_message_decline_decline_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='guest_count',
        ),
        migrations.AddField(
            model_name='response',
            name='adult_count',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='response',
            name='kids_count',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
